name: Lint and Format Check

on:
  push:
    branches:
      - '**' # Runs on any branch
  pull_request: # Runs on all PRs

jobs:
  lint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm eslint . --max-warnings=0

      - name: Run Prettier Check
        run: pnpm prettier --check .
